matrix:
  include:
    - name: "Ubuntu Bionic"
      os: linux
      dist: bionic
      language: python
      python: "3.6"
      virtualenv:
        system_site_packages: true
      before_install:
        - sudo apt-get install -y python3-wxgtk4.0
        - pip3 install pyinstaller
      install:
        - true;
      script:
        - python3 -c "import wx; print(wx.version())"
      after_success:
        - pyinstaller smb3-foundry.spec
        - mv dist/smb3-foundry dist/linux-smb3-foundry
      deploy:
        provider: releases
        api_key:
          secure: zapduKP5v3rW86Zczy2bithNEklLL2y1TA/tmyumjgP5hqVyG8oOzDxI0sw4rzQkJWmdXC1t1dV7UzG9lF9FK2IvWrVOTlCH8/wpqReDNLLkUtI+hKIZERCpUC7pFKookIr9CWtjH+rObauPvjv6GjmejJmgncIl2SktCCp1ZBY/d/d2rmUDiyX2xgcRPjExxpLrFskrVdfo6EaQmPZn+X/WQEYY+Aksm8bstsn/0XgXmIy/ey9xP1EF+aLfeK7vRLe3LOgRda6DlcU4LpvXRuk1Y4opgMC943qukJNNlxub8N0iaSCreNQSa2HdY/tar/CAW9WuHeszfGMJgwyaBP15cs1T4WQwHFdr7mDCySnNMo7VjVGH3nsSlQYzlhtiBFiENX/XPg0DLn3IshrOVARQYJ5uvP6n+qLmsiGNMvvfwkmVIopkbuDpZt/0HdgwAXYzsoHJE+NkVc1XZnr3y8J+7RGCA286P05wg1kCGw742LphspIQUD2SrvNpbdRQ2nMJ6JXW8j1MC6AYtmxFUATDbIkZEdwtQN/lYnly9VvezXjN7BAwLu1bFv3Q2nRP90hf9qALOmdXscaSadTauei0MNs2OGclOKFgd/do8ITZKNxKLWzH1UrJ5tMFuGvHS47aQdV5xG31kQORMYKzRa4e88g2h26SlLh1BX6FhwA=
        file: dist/linux-smb3-foundry
        skip_cleanup: true
        prerelease: true
        on:
          tags: true

    - name: "Mac OSX"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell
      before_install:
        - python3 -m pip install --upgrade pip
        - python3 -m pip install wxpython
        - python3 -m pip install pyinstaller
      install:
        - true;
      script:
        - python3 -c "import wx; print(wx.version())"
      after_success:
        - pyinstaller smb3-foundry.spec
        - mv dist/smb3-foundry dist/osx-smb3-foundry
      deploy:
        provider: releases
        api_key:
          secure: zapduKP5v3rW86Zczy2bithNEklLL2y1TA/tmyumjgP5hqVyG8oOzDxI0sw4rzQkJWmdXC1t1dV7UzG9lF9FK2IvWrVOTlCH8/wpqReDNLLkUtI+hKIZERCpUC7pFKookIr9CWtjH+rObauPvjv6GjmejJmgncIl2SktCCp1ZBY/d/d2rmUDiyX2xgcRPjExxpLrFskrVdfo6EaQmPZn+X/WQEYY+Aksm8bstsn/0XgXmIy/ey9xP1EF+aLfeK7vRLe3LOgRda6DlcU4LpvXRuk1Y4opgMC943qukJNNlxub8N0iaSCreNQSa2HdY/tar/CAW9WuHeszfGMJgwyaBP15cs1T4WQwHFdr7mDCySnNMo7VjVGH3nsSlQYzlhtiBFiENX/XPg0DLn3IshrOVARQYJ5uvP6n+qLmsiGNMvvfwkmVIopkbuDpZt/0HdgwAXYzsoHJE+NkVc1XZnr3y8J+7RGCA286P05wg1kCGw742LphspIQUD2SrvNpbdRQ2nMJ6JXW8j1MC6AYtmxFUATDbIkZEdwtQN/lYnly9VvezXjN7BAwLu1bFv3Q2nRP90hf9qALOmdXscaSadTauei0MNs2OGclOKFgd/do8ITZKNxKLWzH1UrJ5tMFuGvHS47aQdV5xG31kQORMYKzRa4e88g2h26SlLh1BX6FhwA=
        file: dist/osx-smb3-foundry
        skip_cleanup: true
        prerelease: true
        on:
          branch: master
          tags: true

    - name: "Windows"
      os: windows
      language: shell # python is not supported yet
      env:
        - PY37PATH=/c/Python37:/c/Python37/Scripts
        - PATH=$PY37PATH:$PATH
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
        - python -m pip install wxpython
        - python -m pip install pyinstaller
      install:
        - true;
      script:
        - python -c "import wx; print(wx.version())"
      after_success:
        - pyinstaller smb3-foundry.spec
        - mv dist/smb3-foundry.exe dist/win-smb3-foundry.exe
      deploy:
        provider: releases
        api_key:
          secure: zapduKP5v3rW86Zczy2bithNEklLL2y1TA/tmyumjgP5hqVyG8oOzDxI0sw4rzQkJWmdXC1t1dV7UzG9lF9FK2IvWrVOTlCH8/wpqReDNLLkUtI+hKIZERCpUC7pFKookIr9CWtjH+rObauPvjv6GjmejJmgncIl2SktCCp1ZBY/d/d2rmUDiyX2xgcRPjExxpLrFskrVdfo6EaQmPZn+X/WQEYY+Aksm8bstsn/0XgXmIy/ey9xP1EF+aLfeK7vRLe3LOgRda6DlcU4LpvXRuk1Y4opgMC943qukJNNlxub8N0iaSCreNQSa2HdY/tar/CAW9WuHeszfGMJgwyaBP15cs1T4WQwHFdr7mDCySnNMo7VjVGH3nsSlQYzlhtiBFiENX/XPg0DLn3IshrOVARQYJ5uvP6n+qLmsiGNMvvfwkmVIopkbuDpZt/0HdgwAXYzsoHJE+NkVc1XZnr3y8J+7RGCA286P05wg1kCGw742LphspIQUD2SrvNpbdRQ2nMJ6JXW8j1MC6AYtmxFUATDbIkZEdwtQN/lYnly9VvezXjN7BAwLu1bFv3Q2nRP90hf9qALOmdXscaSadTauei0MNs2OGclOKFgd/do8ITZKNxKLWzH1UrJ5tMFuGvHS47aQdV5xG31kQORMYKzRa4e88g2h26SlLh1BX6FhwA=
        file: dist/win-smb3-foundry.exe
        skip_cleanup: true
        prerelease: true
        on:
          branch: master
          tags: true
