name: Build SMB3 Foundry

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ '**' ]
    tags-ignore: [ '*' ]

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {os: ubuntu-20.04, exe: 'smb3-foundry', prefix: 'linux', suffix: '', python-version: '3.8'}
        - {os: windows-2019, exe: 'smb3-foundry.exe', prefix: 'win64', suffix: '.exe', python-version: '3.8'}
        - {os: macos-latest, exe: 'smb3-foundry', prefix: 'osx', suffix: '', python-version: '3.8'}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Get Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller smb3-foundry.spec
          mv dist/${{ matrix.config.exe }} dist/${{ matrix.config.prefix }}-smb3-foundry${{ matrix.config.suffix }}